/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salsa_28052024;

/**
 *
 * @author Salsabilla Humayhira saputri
 */
public class FromStudentRecord extends javax.swing.JFrame {

    /**
     * Creates new form FromStudentRecord
     */
    public FromStudentRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMathGrade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEnglishGrade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtScienceGrade = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 50, 20);
        getContentPane().add(txtName);
        txtName.setBounds(110, 10, 240, 22);

        jLabel2.setText("Address");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 50, 20);
        getContentPane().add(txtAddress);
        txtAddress.setBounds(110, 50, 240, 30);

        jLabel3.setText("Age");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 21, 16);
        getContentPane().add(txtAge);
        txtAge.setBounds(110, 90, 240, 22);

        jLabel4.setText("MathGrade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 70, 16);
        getContentPane().add(txtMathGrade);
        txtMathGrade.setBounds(110, 130, 240, 22);

        jLabel5.setText("EnglishGrade");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 70, 16);
        getContentPane().add(txtEnglishGrade);
        txtEnglishGrade.setBounds(110, 170, 240, 22);

        jLabel6.setText("ScienceGrade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 70, 16);
        getContentPane().add(txtScienceGrade);
        txtScienceGrade.setBounds(110, 210, 240, 22);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(40, 240, 310, 23);

        jLabel7.setText("Average");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 270, 50, 16);
        getContentPane().add(txtAverage);
        txtAverage.setBounds(110, 270, 240, 22);

        setSize(new java.awt.Dimension(427, 319));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        p2_26032024.StudentRecord student = new p2_26032024.StudentRecord();
        student.setName(txtName.getText());
        student.setAddress(txtAddress.getText());
        student.setAge(Integer.parseInt(txtAge.getText()));
        student.setMathGrade(Double.parseDouble(txtMathGrade.getText()));
        student.setEnglishGrade(Double.parseDouble(txtEnglishGrade.getText()));
        student.setScienceGrade(Double.parseDouble(txtScienceGrade.getText()));
        ////
        txtAverage.setText(student.getAverage()+"");
                
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromStudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtEnglishGrade;
    private javax.swing.JTextField txtMathGrade;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScienceGrade;
    // End of variables declaration//GEN-END:variables
}
